-- 멤버 테이블 생성
drop table if exists member CASCADE;
create table member
(
--  generated by default as identity : autoincrement
    id bigint generated by default as identity,
    name varchar(255),
    primary key (id)
);