-- 멤버 테이블 생성
drop table if exists member CASCADE;
create table member
(
--  generated by default as identity : autoincrement
    id bigint generated by default as identity,
    name varchar(255),
    primary key (id)
);

-- ACCOUNT 테이블 생성
drop table if exists account CASCADE;
CREATE TABLE account
(
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY,
    username    VARCHAR(50) NOT NULL UNIQUE,
    password    VARCHAR(255) NOT NULL,
    role        VARCHAR(20) NOT NULL,
    created_at  TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at  TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);
-- 인덱스 추가
CREATE INDEX idx_account_username ON account (username);
-- 역할 제한
ALTER TABLE account ADD CONSTRAINT CHK_account_role CHECK (role IN ('ADMIN', 'USER', 'GUEST'));
